name: Examples

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create Virtual Environment
        run: python -m venv venv && source venv/bin/activate
      - name: Install Packages
        run: apt install qt5-default && pip install --upgrade pip &&
             pip install -r requirements.txt
      - name: Run Characterisation Example
        run: python3 examples/characterisation.py
      - name: Run Interferometer Example
        run: python3 examples/interferometer.py
      - name: Run PTI Inversion Example
        run: python3 examples/pti_inversion.py
