name: Examples

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create Virtual Environment
        run: python -m venv venv && source venv/bin/activate
      - name: Install Packages
        run: pip install --upgrade pip
             pip install fastcrc numpy pandas scipy dacite pyserial h5py nptyping[complete] \
             beartype commented-configparser overrides tqdm
      - name: Run Characterisation Example
        run: python3 examples/characterisation.py
      - name: Run Interferometer Example
        run: python3 examples/interferometer.py
      - name: Run PTI Inversion Example
        run: python3 examples/pti_inversion.py
