name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Packages |
        run: python -m pip install --upgrade pip
             pip install fastcrc numpy pandas scipy dacite pyserial h5py nptyping[complete] \
             beartype commented-configparser green
      - name: Run Hardware Tests
        run: green tests/hardware.py
      - name: Run Algorithm Tests
        run: green tests/algorithm.py
